require: rubocop-rspec

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Lint/ToJSON:
  Enabled: false

Lint/UselessMethodDefinition:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Severity: warning
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Max: 200
  Severity: warning

Metrics/ParameterLists:
  Max: 6
  MaxOptionalParameters: 6

Metrics/MethodLength:
  Max: 15

Naming/BinaryOperatorParameterName:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

RSpec/MessageSpies:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '[]'
    '%I': '[]'
    '%r': '{}'
    '%w': '[]'
    '%W': '[]'

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
  ConsistentQuotesInMultiline: false

Security/YAMLLoad:
  Enabled: false
