name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.6]

    steps:
    - uses: actions/checkout@master

    - name: Set up the Ruby version
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Ruby gem cache
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Set up the environment
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Runs tests
      run: bundle exec rspec

  rubocop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.3', '3.4.0-preview2']

    steps:
    - uses: actions/checkout@master

    - name: Set up the Ruby version
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Ruby gem cache
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Set up the environment
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Runs Rubocop
      run: bundle exec rubocop
